# Generated by Django 3.1.6 on 2021-08-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('sender_name', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=25)),
                ('date_of_transfer', models.DateField()),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
