# Generated by Django 3.1.6 on 2021-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_transactions_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_of_transfer',
            field=models.CharField(max_length=100),
        ),
    ]
